spring:
  data:
    mongodb:
      database: schulatlas
aws:
  region: eu-central-1
  access:
    key:
      id: top-secret
      secret: top-secret
  s3:
    audio:
      bucket: schulatlas
google:
  api:
    geo: top-secret
security:
  jwt:
    secret: top-secret